### ISSUE TITLE
Pass extra query parameters to createFile

### ISSUE THREAD

**Issue by gilbsgilbs** [pCloud/pcloud-sdk-java#1]
Hi,

Currently, the `createFile` method invariably passes [`renameifexists=true` to the API](https://github.com/pCloud/pcloud-sdk-java/blob/85f477c48837ee6e903100fbf15d5d20cbbe5302/java-core/src/main/java/com/pcloud/sdk/internal/RealApiClient.java#L189). I'm in a case where I need to overwrite any existing files (and create new revisions). Unless I'm missing something, the SDK doesn't seem to allow this at the moment. As a workaround, I have to upload the file with a random name and rename it with the real name I want, but this doesn't deal well with shared files (see https://github.com/PhilippC/keepass2android/pull/604#issuecomment-435576826), and anyways I'm not sure this strategy is really risk-free and advisable.

There should be a way to pass extra query parameters or configuration to `createFile` (that would for instance also allow setting `nopartial` to `false`). Maybe it could even be designed in a way that could also be extended to other methods.

Thanks.

**Comment by georgi-neykov-hub** [comment]
Hello,
We've just pushed an [update](https://github.com/pCloud/pcloud-sdk-java/commit/4f847794821cf96d6b6ccacc380b166a24bc273b) to the SDK, the `ApiClient.createFile()` has an additional parameter that allows configuring the `renameifexists` and `nopartial` API call parameters so I am closing the issue. 
There also a new version pushed to Bintray, see the dependency badges in the README file.

Please open new issues if you need something else to be changed/added.

**Comment by gilbsgilbs** [comment]
Great @georgi-neykov-hub, thank you very much for your work.
