### ISSUE TITLE
Request: add Activity to the SDK

### ISSUE THREAD

**Issue by mjenny** [pCloud/pcloud-sdk-java#10]
Hi

I'm in the middle of using your SDK in an Android app.
Regarding the authentication process I had a look at your example code.

Now I'm wondering if there is a reason the Android authentication specific files (located here: https://github.com/pCloud/pcloud-sdk-java/tree/master/android/src/main/java/com/pcloud/sdk) are not part of the actual compiled SDK.

**Comment by georgi-neykov-hub** [comment]
Hello,

The [AuthorizationActivity](https://github.com/pCloud/pcloud-sdk-java/blob/master/android/src/main/java/com/pcloud/sdk/AuthorizationActivity.java) class and support definitions are distributed as a separate artifact as they depend on Android runtime classes (`Activity`). The `java-core` artifact can be used on any supported JVM language project. 
See the [Android](https://github.com/pCloud/pcloud-sdk-java#android) section of the project's README file for instructions on how to add it to a Gradle-based Android project.

**Comment by mjenny** [comment]
Hi,

Sorry completely missed that.
