### ISSUE TITLE
Account access grant error: Error while loading url 'https://cdn.safecharge.com/jstag/managed/...cc_complete.js'

### ISSUE THREAD

**Issue by SailReal** [pCloud/pcloud-sdk-java#12]
Using the `WebView` of the `AuthorizationActivity` I often get a `Account access grant error`. Often I need to start this  `Activity` a few times (sometimes 2, sometimes 10) in a row until this error isn't thrown anymore and the auth works as expected.

This issue can be reproduced using the `MainActivity` of the `sample-android` module too.

The complete log entry is:

```
com.pcloud.sdk.sample D/pCloud: Account access grant error:
    Error while loading url 'https://cdn.safecharge.com/jstag/managed/34ff9876-a972-4543-9110-773743828c28/38855e706ea535cc_complete.js':
    -1: net::ERR_FAILED
```

<img src="https://user-images.githubusercontent.com/1786772/111687142-3a1e4b80-882a-11eb-9580-0667f18aed1f.gif"  height="600" />

**Comment by georgi-neykov-hub** [comment]
@SailReal there's something going on with the SDK from one of the payment providers pCloud's web application is using. I've forwarded the issue to the responsible team. I will update the issue when there's a fix.

**Comment by SailReal** [comment]
Seems to be fixed.
