### ISSUE TITLE
Only one API token per pCloud-application per user

### ISSUE THREAD

**Issue by SailReal** [pCloud/pcloud-sdk-java#18]
Your SDK only allows one valid API token per pCloud-application per user. The second auth is revoking the previous token with errorCode 2095.

Steps to reproduce:

1. Install an app that uses pcloud-sdk-java on two devices
2. Login device 1
3. Login device 2 (with the same pCloud-account used in device 1)
4. Try interact with pCloud on device 1

Is this limitation intended in this way?

**Comment by mjenny** [comment]
@georgi-neykov-hub can you give us some insight on if this is intended behavior?

**Comment by SailReal** [comment]
The problem seems to be fixed :+1:

**Comment by SailReal** [comment]
This problem happens again.

**Comment by mjenny** [comment]
@georgi-neykov-hub any update on this issue?

**Comment by dknchris** [comment]
Can we have an official update on this? This is a highly reproducible issue. There must be a method within the SDK to refresh tokens.

**Comment by Fentadroid** [comment]
It seems no one cares about that but it's a really bad issue.... I hope we can get an answer from someone. That's not a limit of free accounts, I have a  monthly paid account and the issue is always reproducible.

**Comment by georgi-neykov-hub** [comment]
> It seems no one cares about that but it's a really bad issue.... I hope we can get an answer from someone. That's not a limit of free accounts, I have a monthly paid account and the issue is always reproducible.

I have just tested the issue by doing the following:
1. Building & running the sample application from this project,
2. Logged in successfully with the same EU-based user multiple times (also tested with a US-based user).
3. Collect and verify all generated tokens being active and can be used to make API calls.

Can you provide some more details: 
* Which SDK artifacts are you using and what version?
* Are you just using the `android` module to obtain a token or you're also using the `core` module to make requests?
* Are you making calls on the correct API endpoint? Note that US-based accounts must use `api.pcloud.com` and EU-based accounts use `eapi.pcloud.com` (there's an `e` at the front). The correct endpoints are are turned as parameters together with the access token upon successful authentication and authorization.
* Does the issue occur after a specific call?

Thank you

**Comment by georgi-neykov-hub** [comment]
> Can we have an official update on this? This is a highly reproducible issue. There must be a method within the SDK to refresh tokens.

@dknchris, what flow are you using? (code vs token). Note that the token flow does not allow refreshing of tokens, obtaining a new token goes through the OAuth page and data from the redirect.

Can you provide some more details like SDK version, any known reproduction steps? Can you also check #22 to see if you don't have a similar problem with making calls on right API host?

**Comment by dknchris** [comment]
> @dknchris, what flow are you using? (code vs token). Note that the token flow does not allow refreshing of tokens, obtaining a new token goes through the OAuth page and data from the redirect.
I'm using the core module and token based authentication using AppAuth since I need the CustomTabs approach rather than WebView approach which is not supported by Google Sign in.

Code based authentication fails when using AppAuth for some reason. Tried the same with Yandex and it works fine. Just something to note.

If this SDK starts using CustomTabs like AppAuth, it would solve this issue for me and I can use the SDK methods itself with code based authentication.

**Comment by georgi-neykov-hub** [comment]
@Fentadroid , @mjenny , @SailReal there an update to the OAuth API from the backend team that's live since last night. Can you check if the issue is still reproducible?

**Comment by SailReal** [comment]
@georgi-neykov-hub  I can no longer reproduce the problem but this was also the case before:

![Screenshot from 2021-12-09 15-01-53](https://user-images.githubusercontent.com/1786772/145410452-535f336f-9a61-4de7-8991-cf355fd07e2b.png)

Does the "update of the OAuth API" you mentioned include an increase in the number of tokens per user account and app on the backend side?

**Comment by georgi-neykov-hub** [comment]
> @georgi-neykov-hub  I can no longer reproduce the problem but this was also the case before:
> 
> ![Screenshot from 2021-12-09 15-01-53](https://user-images.githubusercontent.com/1786772/145410452-535f336f-9a61-4de7-8991-cf355fd07e2b.png)
> 
> Does the "update of the OAuth API" you mentioned include an increase in the number of tokens per user account and app on the backend side?
> 

Multiple tokens were allowed even before the update. We weren't able to reproduce the problem locally, but found a potential race condition affecting how token expiration dates are being recorded and handled.

**Comment by mjenny** [comment]
@georgi-neykov-hub I tested this as well and couldn't reproduce the issue either.

**Comment by dknchris** [comment]
I'm still able to reproduce the issue persistently.

**Comment by cmoijulien** [comment]
I reproduce this issue with latest library version (1.8.1). 
I also think that it is necessary to do the tests on mobile devices.
Can you reopen this issue ?
