### ISSUE TITLE
Bintray shutting down its services - Download Links in `README.md`

### ISSUE THREAD

**Issue by mjenny** [pCloud/pcloud-sdk-java#19]
I  just realized that the download links inside the `README.md` are pointing to Bintray which is shutting down it's services by May 31st 2021:
![grafik](https://user-images.githubusercontent.com/4191545/113842799-57906680-9793-11eb-9a8a-7948cdf9d7b4.png)

Maybe you want to consider publishing the packages somewhere else or if you already do so consider adjusting the download links in `README.md`.

**Comment by georgi-neykov-hub** [comment]
The Web frontend is being shutdown on 31 May. JCenter's Maven repository will be working until Feb 2022. We are in the process of migrating to Maven Central, the links in the documentation will be updated once it's done.

**Comment by mjenny** [comment]
Thanks for the clarification.
