### ISSUE TITLE
Version 1.4.0 is not available through JCenter

### ISSUE THREAD

**Issue by mjenny** [pCloud/pcloud-sdk-java#20]
I realized that the newly published version `1.4.0` is not available through JCenter: 
- https://mvnrepository.com/artifact/com.pcloud.sdk/java-core (latest available version: `1.3.0`)
- https://mvnrepository.com/artifact/com.pcloud.sdk/android (latest available version: `1.3.0`)
Can you please analyze why this package wasn't published although it is present in your Bintray repository?

**Comment by georgi-neykov-hub** [comment]
@mjenny , the SDK artifacts are now available in Maven Central.
