### ISSUE TITLE
error com.pcloud.sdk.ApiError: 2094 - Invalid 'access_token' provided

### ISSUE THREAD

**Issue by theli** [pCloud/pcloud-sdk-java#22]
Hi, I am integrating sdk into Android app and get access_token error when making api calls.

Using the provided sample I init authentication flow.

```
        val authIntent = AuthorizationActivity.createIntent(
            requireContext(),
            AuthorizationRequest.create()
                .setType(AuthorizationRequest.Type.TOKEN)
                .setClientId(“xxxx”)
                .setForceAccessApproval(true)
                .addPermission("manageshares")
                .build()
        )
```

I log in successfully and obtain access_token from authData like this:
```
val authData = AuthorizationActivity.getResult(data)
            val apiClient = PCloudSdk
                .newClientBuilder()
                .authenticator(Authenticators.newOAuthAuthenticator(authData.token))
                .create()

```
…and init apiClient with access token as param

```
ApiClient apiClient = PCloudSdk.newClientBuilder()
                .authenticator(Authenticators.newOAuthAuthenticator(<your OAuth access token here>))
                // Other configuration...
                .create();
```

Then when I make API call to list root content I get an error com.pcloud.sdk.ApiError: 2094 - Invalid 'access_token' provided. What am I doing wrong?

**Comment by sixtsense** [comment]
Hallo, 
Thanks for reaching out at us. From the looks of things you are not applying the "authData.apiHost" parameter to the apiClient builder. Looks like we have missed to add this in the documentation of the last SDK update.

**Comment by panovvitalik** [comment]
> Hallo, Thanks for reaching out to us. From the looks of things you are not applying the "authData.apiHost" parameter to the apiClient builder. Looks like we have missed to add this in the documentation of the last SDK update.

I was faced the same issue. And your advice is resolved the issue.
I think you should add this information to the documentation. It;s very! important

**Comment by Anready** [comment]
> Hallo, Thanks for reaching out to us. From the looks of things you are not applying the "authData.apiHost" parameter to the apiClient builder. Looks like we have missed to add this in the documentation of the last SDK update.

What i need to put in this method
