### ISSUE TITLE
access_token expires when user signs in on the second device

### ISSUE THREAD

**Issue by theli** [pCloud/pcloud-sdk-java#23]
Here is the case when user is logged on first device, then signs into the same account on another device. Same moment his access token on first device is revoked and I am seeing error. Why is it happening?
`    com.pcloud.sdk.ApiError: 2095 - Revoked 'access_token' provided, you need to re-authorize the application.
`

**Comment by Fentadroid** [comment]
Hello, there is another open thread about this issue:

https://github.com/pCloud/pcloud-sdk-java/issues/18

This is the answer from the support team by email:

[CODE]
Hello,

Thank you for letting us know.

The developers are aware of the issue and I hope that a fix will be available soon but we can not provide an ETA.

If you have any additional questions, please don't hesitate to ask.

Regards,
George Lewis
pCloud's Technical Support
[/CODE]

**Comment by theli** [comment]
Thank you, @Fentadroid. I wish I found #18 before I decided to use this sdk.

**Comment by theli** [comment]
@georgi-neykov-hub

**Comment by theli** [comment]
duplicate of #18
