### ISSUE TITLE
Feature Request: Support API file.checksumfile

### ISSUE THREAD

**Issue by ferenc-hechler** [pCloud/pcloud-sdk-java#25]
The `RemoteFile ` class has an attribute `hash` which "... can be used to determine if two files are the same ..." as stated here:
https://docs.pcloud.com/structures/metadata.html

Unfortunately it is not documented how to calculate the hash offline. 
So, the hash can not be calculated for files, which are not uploaded.

There exsists an API call `file/checksumfile`, which returns a well known message digest MD5/SHA1/SHA256:
https://docs.pcloud.com/methods/file/checksumfile.html

But this API call is not implemented in the pcloud-java-sdk.

For my usecase I want to maintain an offline database and want to check for duplicates, before uploading files.

So, what would help me is a documenation how the "hash" attribute for a RemoteFile can be calculated or to have the API call checksumfile.

**Comment by ferenc-hechler** [comment]
PING

**Comment by georgi-neykov-hub** [comment]
@ferenc-hechler expect an library version with the `checksumfile` API added in the next couple of days. There a few other request and changes which are also underway.

**Comment by georgi-neykov-hub** [comment]
@ferenc-hechler, version 1.7.0 of the SDK adds methods for obtaining [cheksums](https://pcloud.github.io/pcloud-sdk-java/java-core/com.pcloud.sdk/-api-client/index.html#-436249725%2FFunctions%2F-1778586320). I will keep open the issue for some time for feedback.

**Comment by ferenc-hechler** [comment]
Just tested from the sources tag "1.7.0" and getChecksums(id/path) works as expected.
Tested in EU and SHA1 and SHA256 is returned and MD5 is null (as expected).
Thanks for implementing this, issue and PR can be closed.  🥇
