### ISSUE TITLE
Download link is not accessible from another device

### ISSUE THREAD

**Issue by fnishihara** [pCloud/pcloud-sdk-java#27]
I am uploading a file and trying to download on another device but the download link shows this message:
"This link was generated for another IP address. Try previous step again."
I am using the following code:

```
call = apiClient.createFile(
	cpath, 
	file.getName(), 
	DataSource.create(file), 
	new Date(file.lastModified()), 
	listener, 
	UploadOptions.OVERRIDE_FILE);
RemoteFile uploadedFile = call.execute();
FileLink filelink = uploadedFile.createFileLink();
String resp = filelink.bestUrl().toString();
```
Is there a way to make the download file accessible (public link) for everyone?

**Comment by georgi-neykov-hub** [comment]
@fnishihara, file links are designed for immediate use (from the same network used to create them) and have a very limited lifespan. PCloud's API provides means to generate a "public links"  for a given file, folder or a collection of files/folders which are long-lived and can be shared. The functionality is documented [here](https://docs.pcloud.com/methods/public_links/) but unfortunately is not currently part of this SDK.
