### ISSUE TITLE
Feature Request: ApiClient.stat / ApiClient.metadata

### ISSUE THREAD

**Issue by Finni123** [pCloud/pcloud-sdk-java#28]
There is no way to properly download an Image on android, or am I missing something really obvious?

`stat` and `metadata` don't exist in the [Java API Client](https://github.com/pCloud/pcloud-sdk-java/blob/master/java-core/src/main/java/com/pcloud/sdk/ApiClient.java) and I need them for this. The java sample uses a `File` for this, but unfortunately, that doesn't work on android since the pcloud files don't appear in the regular folder structure, thus I have to use the API.

(Also, `getthumb` would be great, too)

**Comment by georgi-neykov-hub** [comment]
@Finni123 , 
* For obtaining the metadata of a single file by its file id you can use [`PCloudApiClient.loadFile()`](https://pcloud.github.io/pcloud-sdk-java/java-core/com.pcloud.sdk/-api-client/load-file.html). 
* For getting a list of files and their metadata of folder by its folder id you can use the [`PCloudApiClient.loadFolder()`](https://pcloud.github.io/pcloud-sdk-java/java-core/com.pcloud.sdk/-api-client/list-folder.html).
* Downloads of files are done via one of the variants of [`PCloudApiClient.download()`](https://pcloud.github.io/pcloud-sdk-java/java-core/com.pcloud.sdk/-api-client/download.html). 
Two of the variants will open and return a `BufferedSource` (see Okio's [docs](https://javadoc.io/doc/com.squareup.okio/okio/1.17.5/okio/BufferedSource.html)) streams which you can use to 
write the contents of a remote (@PCloud) file to some arbitrary destination as you please. The other download()overloads accept a [`DataSink`](https://pcloud.github.io/pcloud-sdk-java/java-core/com.pcloud.sdk/-data-sink/index.html), which is an abstraction over a destination for the bytes of the file to be downloaded. There is a factory method that accepts a `java.io.File` as a destination, you can also roll your own implementation.
