### ISSUE TITLE
Problem when upload files

### ISSUE THREAD

**Issue by JoynerPerez1987** [pCloud/pcloud-sdk-java#3]
When I upload a file, it is uploaded correctly but when I try to upload a second file, it never uploads and stays loaded indefinitely.

**Comment by krishna444** [comment]
I have one question: I have uploaded a file(testFile.pdf) into my pcloud space. Now I want to download the same file, I need to create RemoteFile object. Is there any way to create a RemoteFile instance with a file name?
Or 
any better approach to download a file in pcloud by using the name of the file.

Thanks in advance!

Krishna

**Comment by georgi-neykov-hub** [comment]
Thank you for reaching out. Can you give me some more details, are you using one of the `ApiClient.createFile()` methods? Are you reusing the `ProgressListener` or creating new instances for each call? Any hint on reproduction is welcome. I can also recommend you to try using the [pCloud Networking Library](https://github.com/pCloud/pcloud-networking-java) and directly use the documented calls in [pCloud's API docs](https://docs.pcloud.com/methods/file/uploadfile.html).
