### ISSUE TITLE
createfile() from a datasource with unknown contentlength gets stuck

### ISSUE THREAD

**Issue by ferenc-hechler** [pCloud/pcloud-sdk-java#30]
I want to create a file from an InputStream. So, I do not know in advance, how long this stream (=content) is.
So, I created a InputStreamDataSource the following way:

```
	public static class InputStreamDataSource extends DataSource {
		private InputStream in;
		public InputStreamDataSource(InputStream in) {
			this.in = in;
		}
		@Override
		public void writeTo(BufferedSink sink) throws IOException {
			OutputStream out = sink.outputStream();
			byte[] buf = new byte[4096];
			while (true) {
				int cnt = in.read(buf);
				if (cnt <= 0) {
					break;
				}
				out.write(buf, 0, cnt);
			}
		}
	}
```

The file uploaded is started using createFile():

```
RemoteFile rFile = apiClient.createFile(folderId, filename, new InputStreamDataSource(in), UploadOptions.OVERRIDE_FILE).execute();
```

But, the call to execute() does not return. It is stuck in HeadersReader.readLine():

```
Thread [main] (Suspended)	
	HeadersReader.readLine() line: 29	
	Http1ExchangeCodec.kt line: 178	
	Exchange.readResponseHeaders(boolean) line: 106	
	CallServerInterceptor.intercept(Interceptor$Chain) line: 79	
	RealInterceptorChain.kt line: 109	
	ConnectInterceptor.intercept(Interceptor$Chain) line: 34	
	RealInterceptorChain.kt line: 109	
	CacheInterceptor.intercept(Interceptor$Chain) line: 95	
	RealInterceptorChain.kt line: 109	
	BridgeInterceptor.kt line: 83	
	RealInterceptorChain.kt line: 109	
	RetryAndFollowUpInterceptor.intercept(Interceptor$Chain) line: 76	
	RealInterceptorChain.kt line: 109	
	AccessTokenAuthenticator.intercept(Interceptor$Chain) line: 50	
	RealInterceptorChain.kt line: 109	
	GlobalRequestInterceptor.intercept(Interceptor$Chain) line: 46	
	RealInterceptorChain.kt line: 109	
	RealCall.kt line: 201	
	RealCall.kt line: 154	
	OkHttpCall<T>.execute() line: 42	
	PCloudUploader.uploadFile(Path, InputStream) line: 123	
	...
```

For testing I patched the InputStreamDataSource and returned exactly the number of bytes, that my InputStream provides (856 bytes):

```
	public static class InputStreamDataSource extends DataSource {
		private InputStream in;
		public InputStreamDataSource(InputStream in) {
			this.in = in;
		}
[+]		@Override
[+]	    public long contentLength() {
[+]	        return 856;
[+]	    }
		@Override
		public void writeTo(BufferedSink sink) throws IOException {
			...
		}
	}
```

Now the upload works.

The abstract implementation for DataSource return -1 for contentLength() and is documented as follows:

```
    /**
     * @return the data source length.
     * <p>
     * Override this method to provide the size of the data
     * to be written, if known in advance, otherwise return -1.
     */
    public long contentLength() {
        return -1;
    }
```

So, I assume, it should work with -1, but it doesnt.
Any ideas, how to fix this?

**Comment by georgi-neykov-hub** [comment]
@ferenc-hechler the `DataSource.contentLength()` will be used when building a POST request with a multipart body, it's just passed to Okhttp's request builder APIs. Can you check if the issue is still occurring with the following version of your `InputStreamDataSource`?:

```java

public static class InputStreamDataSource extends DataSource {
        private final InputStream in;
        public InputStreamDataSource(InputStream in) {
            this.in = in;
        }
        @Override
        public void writeTo(BufferedSink sink) throws IOException {
            sink.writeAll(Okio.source(in));
        }
    }
```

**Comment by ferenc-hechler** [comment]
I tried your proposal and it has the same behaviour.
The upload hangs in HeadersReader.readLine().
Adding a method contentLength(), which returns the correct number of bytes, works.

**Comment by georgi-neykov-hub** [comment]
@ferenc-hechler let me sniff the HTTP calls and reproduce them with Postman/curl/... to pinpoint where the issue is occurring and I will reach back.

**Comment by georgi-neykov-hub** [comment]
@ferenc-hechler the behavior is due to a bug resulting in multipart body POST request without a `Content-Length` header. The bigger problem is that due to compatibility reasons the pCloud's HTTP API does not support "streaming" POST requests, nor requests with `Transfer-Encoding: chunked` headers, thus no easy and performant way to upload a file with an unknown length. 
A workaround for the problem is to specify the input stream size upon download, or save the stream to a file, then upload the file.
The new version of the SDK (1.7.0) does not allow returning `-1L` from `DataSource.contentLength()` to address the issue.

**Comment by ferenc-hechler** [comment]
Just tested it, returning "-1" throws an exception. I am using now a temp file to write the stream into it and then upload the temp file.
