### ISSUE TITLE
how to import?

### ISSUE THREAD

**Issue by VoidK2** [pCloud/pcloud-sdk-java#32]
i have append "implementation 'com.pcloud.sdk:java-core:1.7.0'" in my build.gradle ,why is still not import, and i cant use that.

**Comment by georgi-neykov-hub** [comment]
All SDK artifacts are published to Maven Central, you can follow the instructions at the 'java-core' artifact's [page](https://search.maven.org/artifact/com.pcloud.sdk/java-core/1.7.0/pom).
