### ISSUE TITLE
How to list shared folders with Java SDK

### ISSUE THREAD

**Issue by PhilippC** [pCloud/pcloud-sdk-java#33]
I am calling `ApiClient.listFolder` using the Java SDK. While https://my.pcloud.com/ shows a folder shared by another user, the `listFolder` call does not include this shared folder. How can I list/access this folder using the Java SDK?

**Comment by georgi-neykov-hub** [comment]
@PhilippC , version `1.8.0` of the library is live with the necessary changes to make shared folders visible. I will keep the issue open waiting for feedback.

**Comment by PhilippC** [comment]
after updating to 1.8.1 (from 1.2.0) I needed to change my code replacing the line

            Intent authIntent = AuthorizationActivity.createIntent(castedActivity, this.clientId);

with

            AuthorizationRequest req = AuthorizationRequest.create()
                    .setClientId(this.clientId)
                    .setType(AuthorizationRequest.Type.TOKEN)
                    .setForceAccessApproval(true)
                    .build();

            Intent authIntent = AuthorizationActivity.createIntent(castedActivity, req);

Unfortunately, I now get "This 'redirect_uri' is not authorized":

![image](https://user-images.githubusercontent.com/5421734/161521564-bf67a818-dae0-4cb3-ac05-b34811c58e4b.png)

As it is working with 1.2.0 I suspect that my app configuration is correct, but maybe I'm not using the AuthorizationRequest not correctly?

**Comment by sixtsense** [comment]
@PhilippC As of version 1.5.0 of the pCloud Java SDK there have been changes to the Uri scheme required for the redirect to work. You must change the redirect Uri in your pCloud application (https://docs.pcloud.com/my_apps/) to - 'pcloud-oauth://{your.application.package}'

**Comment by PhilippC** [comment]
👍 that solved my issue.

Accessing shared folders is now working, thanks a lot!

**Comment by PhilippC** [comment]
unfortunately I never found the time to integrate this feature in my app. Now I finally wanted to do so and made some changes to the code, so it should work with access to the full pCloud (previously I only offered Applications-folder access) and I was expecting shared folders to work as well.
I created a shared folder from a different pCloud account and it shows with this icon in my.pcloud.com:

![grafik](https://github.com/pCloud/pcloud-sdk-java/assets/5421734/4ada0018-8c49-4aad-bac6-b0d0dce4213b)

Unfortunately, `listFolder` does not return an element in `children()` for this folder. Do I need to do something differently?

**Comment by georgi-neykov-hub** [comment]
@PhilippC let me build a sample with shared folders  and I will reach out.

**Comment by PhilippC** [comment]
> As of version 1.5.0 of the pCloud Java SDK there have been changes to the Uri scheme required for the redirect to work. You must change the redirect Uri in your pCloud application (https://docs.pcloud.com/my_apps/) to - 'pcloud-oauth://{your.application.package}'

While trying to make this change to the production app, I realized that the app was created by one of the contributors and not myself. Unfortunately his account seems to be deleted (https://github.com/PhilippC/keepass2android/pull/2388#issuecomment-1799771771). Is it possible to move the app to my pCloud account or at least restore his account? The app is used by >1.000.000 users (not all of them use pCloud of course, but it should still be quite a few). I would like to avoid them having to re-authenticate if I change the clientId. (Sorry for asking this here but I didn't find a better contact point)

**Comment by PhilippC** [comment]
@georgi-neykov-hub  any news on this?

**Comment by sixtsense** [comment]
@PhilippC Hello, sorry for the delayed response, please contact <support@pcloud.com> for further assistance with this matter.

**Comment by PhilippC** [comment]
@georgi-neykov-hub Can you maybe still share the example you mentioned in https://github.com/pCloud/pcloud-sdk-java/issues/33#issuecomment-1794466752?

**Comment by sixtsense** [comment]
Hello, @PhilippC as my last comment stated, a new version of the pcloud-java-sdk (1.9.1) is now available to download from maven central. In the previous versions of the java-sdk shared folders were excluded from the results of `ApiClient.listFolder` and `ApiClient.loadFolder`.

**Comment by PhilippC** [comment]
thanks for the hint and the update!
