### ISSUE TITLE
Download a file in pCloud

### ISSUE THREAD

**Issue by krishna444** [pCloud/pcloud-sdk-java#4]
I have one question: I have uploaded a file(testFile.pdf) into my pCloud space. Now I want to download the same file, I need to create RemoteFile object. Is there any way to create a RemoteFile instance with a file name?
Or
any better approach to download a file in pCloud by using the name of the file.

Thanks in advance!

Krishna

**Comment by georgi-neykov-hub** [comment]
You can use one of the `ApiClient.listFolder()` methods to get a list of `RemoteFile` entries.

**Comment by krishna444** [comment]
Hi @georgi-neykov-hub, 
I think AppClient.listFolder() should work.  I have to look into the list of remote files to get the file I wanted to download.

Thanks!

Regards,

Krishna
