### ISSUE TITLE
No PIN protection in pcloud executable app or pcloud drive app, vulnerability, feature addition request

### ISSUE THREAD

**Issue by universish** [pCloud/pcloud-sdk-java#44]
I am using the linux pcloud application run file that I downloaded from your website. I am a fedora workstation 40 user. I will request a feature addition. This feature should also come for pcloud drive applications running on all operating systems. we install and run the application portable. We log in. But there is no security lock on the app. I keep a backup of my most important information, all my vital passwords, in pcloud because I trust pcloud. Someone who enters the user password of our computer - which is very easy to learn for hackers etc - can access my pcloud. Because the app has no password. That's why I log out of my pcloud account every time I turn off the computer, you know it's a lot of work. Instead, we can unlock it by entering a pin password linked to the master password. This technology is hello pin technology, which is microsoft account login technology. The pin code can be further protected by adding characters such as but, , and so on. This pin code is linked to the hello password code, when you enter the pin correctly, the password is unlocked, if you enter it incorrectly 3 times, you are logged out of the account and asked for the master password. You should put such a protection. This is also a security vulnerability. 
Since there is no “pcloud-drive” topic in your repo, I had to write this vulnerability and feature addition request under this topic.

**Comment by georgi-neykov-hub** [comment]
@universish, a few words on security and your proposals:
1. Secure your operating system and setup multiple accounts if a single machine is used by different people.
2. Even though your files are safe, PCloud is a cloud storage service, not a password manager. Consider using pCloud's Crypto feature or or pCloud Pass for further increasing your security & ergonomics.

A few words on on your proposal:
1. This is a repository for a software library targetting developers who may want to integrate with pCloud's API. It is not used by any of the official desktop clients offered by pCloud.
2. There's no security vulnerability, and the repository is missing a `pcloud-drive` topic as, again, it has no releation to the functionality and features of pCloud's desktop clients.

I am closing the issue.
