### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by ahanusch** [pCloud/pcloud-sdk-java#5]
There are a few failing tests in `ApiClientIntegrationTest` which is mostly due to the way `entryExistsInFolder()` works. I guess `e.equals(entry)`really requires everything to be identical but when you copy a foler, the ID will differ (just the name remains) and even when moving something, the parentId will change.

**Comment by georgi-neykov-hub** [comment]
@ahanusch Thank you for reaching out. The tests have been updated.
