### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sunday2** [pCloud/pcloud-sdk-java#6]
i compiled the project and met with the following problem:

Could not find artifact pcloud-networking-java:utils-io:jar:1.2.2 in nexus (http://maven.aliyun.com/nexus/content/groups/public/)

i cannot find the jar:
 pcloud-networking-java:utils-io:jar:1.2.2

in any public repository.

**Comment by georgi-neykov-hub** [comment]
@sunday2 , I am closing the issue. This project does not have a dependency on the artifacts you've mentioned, in fact it just depends on OkHttp and Gson. 
* It seems you're actually using the [pcloud-networking-java](https://github.com/pCloud/pcloud-networking-java) project so please create future issues there. 
* `pcloud-networking-java`'s artifacts are published through Bintray and are available in [jcenter](https://jcenter.bintray.com/), also there's a much newer version available ([2.5.0](https://github.com/pCloud/pcloud-networking-java/blob/master/CHANGELOG.md)). 
* The binaries for the artifact you've mentioned are available [here](https://bintray.com/pcloud/pcloud-networking-java/utils-io/1.2.2#files/pcloud-networking-java%2Futils-io%2F1.2.2) or through maven/gradle/ivy/... by following the instructions [here](https://bintray.com/pcloud/pcloud-networking-java/utils-io/1.2.2).

Have a nice day.

**Comment by sunday2** [comment]
@georgi-neykov-hub thanks for the quick response, it is helpful for me. now i met with another issue:
java.lang.NoSuchMethodError: okio.BufferedSource.getBuffer()Lokio/Buffer;

do you have any idea?

**Comment by georgi-neykov-hub** [comment]
What build system and what JVM language are you using?

I would suggest  updating the library to the latest version (2.5.0) before
everything else and create a new issue in the GitHub project if the problem
persists.

На пт, 9.10.2020 г. в 12:21 sunday2 <notifications@github.com> написа:

**Comment by sunday2** [comment]
@sunday2 thanks for the quick response, it is helpful. i am using java, it seems the isuue about version of okio. finally, i use the latest verison of okio and it works.

**Comment by sunday2** [comment]
@georgi-neykov-hub thanks for the quick response, it is helpful. i am using java, it seems the isuue about version of okio. finally, i use the latest verison of okio and it works.
