### ISSUE TITLE
Access to the crypto folder

### ISSUE THREAD

**Issue by sdeleuze** [pCloud/pcloud-sdk-java#7]
I am not sure it is possible to access to the crypto folder with the Java SDK.

Could you please add this capability or let me know how to do if that's already possible?

**Comment by georgi-neykov-hub** [comment]
The feature is not supported currently and there haven't been any plans to add it in the near future.

**Comment by collicalex** [comment]
Hi,
There is still no news from pCloud team?
I'm using there REST API to save my local files to my pCloud account, but I'm not able to access to the Crypto folder as there is no API for that.
And pCloud support team answering there are not providing any support on the API... which is not really helpfull.
